/* Generated By:JavaCC: Do not edit this line. LoveCTreeConstants.java Version 5.0 */
public interface LoveCTreeConstants
{
  public int JJTSTART = 0;
  public int JJTTOP_UNIT = 1;
  public int JJTVAR_FUN = 2;
  public int JJTGLOBAL_VAR_DEF = 3;
  public int JJTCONST_DEF = 4;
  public int JJTFUN_DEF = 5;
  public int JJTFUNC_PARAM_LIST = 6;
  public int JJTFUNC_PARAM_DECL = 7;
  public int JJTPARAM_DECL = 8;
  public int JJTPARAM_DIRECT_DECL = 9;
  public int JJTSTORAGE = 10;
  public int JJTBLOCK = 11;
  public int JJTDECL_LIST = 12;
  public int JJTDECLS = 13;
  public int JJTDECL_SPECIFIERS = 14;
  public int JJTSTORAGE_SPECIFIERS = 15;
  public int JJTTYPE_SPECIFIERS = 16;
  public int JJTTYPE_QUALIFIERS = 17;
  public int JJTINIT_DECL_LIST = 18;
  public int JJTINIT_DECL = 19;
  public int JJTVAR_DECL = 20;
  public int JJTVAR_DIRECT_DECL = 21;
  public int JJTPTR_ARR = 22;
  public int JJTINIT = 23;
  public int JJTINIT_LIST = 24;
  public int JJTSTMT_LIST = 25;
  public int JJTSTMT = 26;
  public int JJTIF_SWITCH_STMT = 27;
  public int JJTCASE_DEFAULT_STMT = 28;
  public int JJTWHILE_FOR_STMT = 29;
  public int JJTJUMP_STMT = 30;
  public int JJTEXPR_STMT = 31;
  public int JJTFUNCALL_STMT = 32;
  public int JJTFUNCALL_PARAMS_LIST = 33;
  public int JJTPARAM_CALL = 34;
  public int JJTEXPR = 35;
  public int JJTASSIGN_EXPR = 36;
  public int JJTASSIGN_OPERATOR = 37;
  public int JJTUNARY_EXPR = 38;
  public int JJTPOSTFIX_EXPR = 39;
  public int JJTPREFIX_EXPR = 40;
  public int JJTCOND_EXPR = 41;
  public int JJTLOGICAL_OR_EXPR = 42;
  public int JJTLOGICAL_AND_EXPR = 43;
  public int JJTINCLUSIVE_OR_EXPR = 44;
  public int JJTEXCLUSIVE_OR_EXPR = 45;
  public int JJTAND_EXPR = 46;
  public int JJTEQUAL_EXPR = 47;
  public int JJTRELATION_EXPR = 48;
  public int JJTSHIFT_EXPR = 49;
  public int JJTADDITIVE_EXPR = 50;
  public int JJTMULTIPLICATIVE_EXPR = 51;
  public int JJTCONSTANT = 52;
  public int JJTNAME = 53;


  public String[] jjtNodeName = {
    "Start",
    "top_unit",
    "var_fun",
    "global_var_def",
    "const_def",
    "fun_def",
    "func_param_list",
    "func_param_decl",
    "param_decl",
    "param_direct_decl",
    "storage",
    "block",
    "decl_list",
    "decls",
    "decl_specifiers",
    "storage_specifiers",
    "type_specifiers",
    "type_qualifiers",
    "init_decl_list",
    "init_decl",
    "var_decl",
    "var_direct_decl",
    "ptr_arr",
    "init",
    "init_list",
    "stmt_list",
    "stmt",
    "if_switch_stmt",
    "case_default_stmt",
    "while_for_stmt",
    "jump_stmt",
    "expr_stmt",
    "funcall_stmt",
    "funcall_params_list",
    "param_call",
    "expr",
    "assign_expr",
    "assign_operator",
    "unary_expr",
    "postfix_expr",
    "prefix_expr",
    "cond_expr",
    "logical_or_expr",
    "logical_and_expr",
    "Inclusive_or_expr",
    "exclusive_or_expr",
    "and_expr",
    "equal_expr",
    "relation_expr",
    "shift_expr",
    "additive_expr",
    "multiplicative_expr",
    "constant",
    "name",
  };
}
/* JavaCC - OriginalChecksum=bb2e19e9634a8c7bad17a1dc21c00ed2 (do not edit this line) */
